apiVersion: v1
kind: Secret
metadata:
  name: devsecops-demo-secret
  namespace: devsecops-demo
  labels:
    app.kubernetes.io/name: devsecops-demo
type: Opaque
stringData:
  APP_SECRET: "secret-placeholder"