apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-digests
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: require-digest-image-references
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - devsecops-demo
      validate:
        message: "Images must be referenced by digest, not by tag."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                  - key: "{{ contains(element.image, '@sha256:') }}"
                    operator: Equals
                    value: false